[build]
    command = "npm run build"
    publish = "public"

[dev]
    command = "npx @11ty/eleventy --serve"
    port = 8080

[functions]
    directory = "netlify/functions"

[redirects]
    [[redirects]]
        from = "/*"
        to = "/index.html"
        status = 200